# Generated by Django 2.2.5 on 2020-03-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200312_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='gusets',
            new_name='guests',
        ),
    ]
