# Generated by Django 2.2.5 on 2020-01-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200120_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gusets',
            field=models.IntegerField(default=1),
        ),
    ]
